# 1. EC2 타입을 파라미터로 입력받아 EC2 인스턴스를 만드는 CFm 템플릿 만들기

# 참고 문서 1 : http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/gettingstarted.templatebasics.html
# 참고 문서 2 : http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
    Description: Choose t2 instance type model.
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceTypeParameter
      ImageId: ami-e21cc38c # Amazon Linux AMI 2017.03.1 (HVM), SSD Volume Type
